# Generated by Django 4.2 on 2023-04-16 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0003_alter_fileinfo_owner_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directory',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compiler.fileinfo'),
        ),
        migrations.AlterField(
            model_name='file',
            name='info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='compiler.fileinfo'),
        ),
    ]
