# Generated by Django 4.2 on 2023-04-20 18:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0006_alter_file_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('start_row', models.IntegerField()),
                ('end_row', models.IntegerField()),
                ('type', models.CharField(choices=[('PROCEDURE', 'Procedure'), ('COMMENT', 'Comment'), ('DIRECTIVE', 'Directive'), ('VARIABLE', 'Variable'), ('INLINE_ASM', 'Inline Assembly'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20)),
                ('status', models.CharField(choices=[('COMPILES_WITH_WARNINGS', 'Compiles with warnings'), ('COMPILE_OK', 'Compiles'), ('COMPILE_ERROR', 'Compile error')], default='COMPILE_OK', max_length=30)),
                ('additional_status_info', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compiler.file')),
            ],
        ),
    ]
