# Generated by Django 4.2 on 2023-04-20 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0007_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='compiler.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='end_row',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='start_row',
            field=models.PositiveIntegerField(),
        ),
    ]
