# Generated by Django 4.2 on 2023-04-21 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compiler', '0008_section_parent_alter_section_end_row_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('PROCEDURE', 'Procedure'), ('COMMENT', 'Comment'), ('DIRECTIVE', 'Directive'), ('VARIABLE', 'Variable'), ('INLINE_ASM', 'Inline Assembly'), ('FUNCTION', 'Function'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
    ]
